# WIP: currently it does not work. The idea here is to understand how to seed cassandra before deploying...
version: '3'
services:
  bikes-cassandra-database:
    image: cassandra:3.11.14
    container_name: bikes-cassandra-db
    restart: always
    ports: 
      - 9042:9042
  bikes-cassandra-init:
    image: cassandra:3.11.5
    container_name: bikes-cassandra-db-init
    depends_on:
      - bikes-cassandra-database
    volumes:
      - ../kubernetes/cassandra.cql:/cassandra.cql:ro
    command: bin/bash -c "echo Initializing cassandra schema... && sleep 30 && cqlsh -u cassandra -p cassandra -f cassandra.cql bikes-cassandra-db"
  bikes:
    image: bikes:0.5.3.3
    container_name: bikes
    depends_on:
      - bikes-cassandra-init
    ports:
      - "8084:8084"
      - "8558:8558"
      - "2553:2553"