apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bikes-cluster-demo
  name: bikes-cluster-demo
  namespace: bikes-cluster-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bikes-cluster-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: bikes-cluster-demo
        actorSystemName: BikeService
    spec:
      containers:
        - name: bikes-cluster-demo
          # image version should match bikes version in build.sbt
          image: bikes:0.5.1
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /ready
              port: 8558
          livenessProbe:
            tcpSocket:
              port: 8558
          ports:
            # akka remoting
            - name: remoting
              containerPort: 2553
              protocol: TCP
            # akka-management bootstrap
            # must match up with contact-point-discovery.port-name for bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8084
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CASSANDRA_CONTACT_POINT1
              value: "cassandra:9042"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: bikes-cluster-1
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: bikes-cluster-1
subjects:
  # Create the default user for the bikes-cluster-1 namespace
  - kind: User
    name: system:serviceaccount:bikes-cluster-1:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
